### ISSUE TITLE
Mgmt Public IP set to False Tuple Error

### ISSUE THREAD

**Issue by Treello** [F5Networks/terraform-azure-bigip-module#1]
I do not want a public IP mapped to my mgmt interface

I am calling the module this way:

module bigip {
  count                      = 2
  source                     = "github.com/F5Networks/terraform-azure-bigip-module?ref=v1.0.0"
  prefix                     = format("fe%s-int-adc0%s",var.zoneid[count.index],var.number[count.index]) #format("%s-bigip-%s",var.prefix,random_id.id.hex)
  f5_ssh_publickey           = file("${path.module}/pub.pub")
  resource_group_name        = local.resource_group_name
  mgmt_subnet_ids            = [{"subnet_id" =  data.azurerm_subnet.mgmt.id, "public_ip" = false, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  mgmt_securitygroup_ids     = [module.mgmt-network-security-group.network_security_group_id]
  external_subnet_ids        = [{ "subnet_id" = data.azurerm_subnet.external.id, "public_ip" = false, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  external_securitygroup_ids = [module.external-network-security-group.network_security_group_id]
  internal_subnet_ids        = [{ "subnet_id" = data.azurerm_subnet.internal.id, "public_ip" = false, "private_ip_primary" = "" }]
  internal_securitygroup_ids = [module.internal-network-security-group.network_security_group_id]
  availabilityZones          = [var.azs[count.index]]
  f5_image_name	             = var.image_name[0]
  f5_product_name            = var.product[0]
}

When i set the public_ip in mgmt_subnet_ids to false i get the following errors

│ Error: Invalid index
│
│   on .terraform\modules\bigip\main.tf line 351, in resource "azurerm_network_interface" "mgmt_nic":
│  351:     private_ip_address_allocation = (length(local.mgmt_public_private_ip_primary[count.index]) > 0 ? "Static" : "Dynamic")
│     ├────────────────
│     │ count.index is 0
│     │ local.mgmt_public_private_ip_primary is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\bigip\main.tf line 351, in resource "azurerm_network_interface" "mgmt_nic":
│  351:     private_ip_address_allocation = (length(local.mgmt_public_private_ip_primary[count.index]) > 0 ? "Static" : "Dynamic")
│     ├────────────────
│     │ count.index is 0
│     │ local.mgmt_public_private_ip_primary is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\bigip\main.tf line 352, in resource "azurerm_network_interface" "mgmt_nic":
│  352:     private_ip_address            = (length(local.mgmt_public_private_ip_primary[count.index]) > 0 ? local.mgmt_public_private_ip_primary[count.index] : null)
│     ├────────────────
│     │ count.index is 0
│     │ local.mgmt_public_private_ip_primary is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on .terraform\modules\bigip\main.tf line 352, in resource "azurerm_network_interface" "mgmt_nic":
│  352:     private_ip_address            = (length(local.mgmt_public_private_ip_primary[count.index]) > 0 ? local.mgmt_public_private_ip_primary[count.index] : null)
│     ├────────────────
│     │ count.index is 0
│     │ local.mgmt_public_private_ip_primary is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.

**Comment by trinaths** [comment]
created INFRAANO-606 for internal tracking,
