### ISSUE TITLE
resource bigip_as3 plugin does not respond and throws a runtime error and crashes

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/terraform-azure-bigip-module#10]
Using terraform provider plugin v1.11.0

terraform version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-providers/bigip v1.11.0

error output:
bigip_as3.app_services: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with bigip_as3.app_services,
│   on bigip.tf line 155, in resource "bigip_as3" "app_services":
│  155: resource "bigip_as3" "app_services" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-bigip_v1.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x133e05e]

goroutine 27 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).APICall(0x0, 0xc0005ed2b0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:177 +0x7e
github.com/f5devcentral/go-bigip.(*BigIP).getForEntity(0x0, 0x1b22a60, 0xc00057eec0, 0xc0005ed350, 0x4, 0x4, 0xa, 0x1b32760, 0xc0001aee78)
        github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:451 +0xe6
github.com/f5devcentral/go-bigip.(*BigIP).getAs3version(0x0, 0x40e, 0x480, 0x1b32760)
        github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/as3bigip.go:302 +0xfb
github.com/f5devcentral/go-bigip.(*BigIP).AddTeemAgent(0x0, 0x1b50700, 0xc0005ed5f8, 0x1b50700, 0xc0002ae3f0, 0x0, 0x0)
        github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/as3bigip.go:417 +0x116
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipAs3Create(0xc0005210a0, 0x1cd1020, 0x0, 0x0, 0x0)
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_as3.go:180 +0x356
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000548b80, 0xc000572c30, 0xc000580460, 0x1cd1020, 0x0, 0x1b95201, 0xc000197488, 0xc000486a50)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000549300, 0xc0005ed8e8, 0xc000572c30, 0xc000580460, 0xc0001974d8, 0xc0001aec30, 0x1b96f00)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0001aebb0, 0x1e7efb0, 0xc0004860f0, 0xc00004f500, 0xc0001aebb0, 0xc0004860f0, 0xc00012ca50)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c8d3a0, 0xc0001aebb0, 0x1e7efb0, 0xc0004860f0, 0xc00004f4a0, 0x0, 0x1e7efb0, 0xc0004860f0, 0xc0005f8000, 0xd7d)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e6000, 0x1e87a98, 0xc000102f00, 0xc00011ea00, 0xc000094690, 0x2441a20, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0001e6000, 0x1e87a98, 0xc000102f00, 0xc00011ea00, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001161d0, 0xc0001e6000, 0x1e87a98, 0xc000102f00, 0xc00011ea00)
        google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-bigip_v1.11.0 plugin crashed!

**Comment by RavinderReddyF5** [comment]
@gwolfis can you please open this bug in : https://github.com/F5Networks/terraform-provider-bigip

**Comment by gwolfis** [comment]
done

https://github.com/F5Networks/terraform-provider-bigip/issues/611
