### ISSUE TITLE
Provider produced inconsitent result after apply

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/terraform-azure-bigip-module#14]
Using the big-ip Terraform in Azure to deploy applications via AS3 templates (.tpl). Adding applications by declaring them via template works. When you want to remove a tenant by creating an 'empty' AS3.tpl like below, the bigip provider produces this error.

 Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to bigip_as3.as3_use_case_6, provider "provider[\"registry.terraform.io/f5networks/bigip\"]" produced an unexpected new value: Root resource was
│ present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

AS3.tpl used to remove the tenant:
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "label": "LAB 2",
        "remark": "Two applications sharing a pool",
        "lab_2": {
            "class": "Tenant"
        }
    }
}

When checking the BIG-IP the tenant did got removed.

Used software versions:
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/f5networks/bigip v1.13.1
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0

**Comment by RavinderReddyF5** [comment]
Hi @gwolfis , issue should be reported on https://github.com/F5Networks/terraform-provider-bigip

**Comment by gwolfis** [comment]
New issue is created:  Provider produced inconsistent result after apply #628
