### ISSUE TITLE
on boarding template for pre-1.2.1 modules breaks due to breaking change in 1.2.1

### ISSUE THREAD

**Issue by mjmenger** [F5Networks/terraform-azure-bigip-module#17]
When using versions of the module earlier than 1.2.1, the following line breaks due to a reference to the latest version of the repository. In particular, the following line

```bash
curl -o /config/cloud/do_w_admin.json -s --fail --retry 60 -m 10 -L https://raw.githubusercontent.com/F5Networks/terraform-azure-bigip-module/main/config/onboard_do.json
```
which can be found at https://github.com/F5Networks/terraform-azure-bigip-module/blob/v1.1.1/f5_onboard.tmpl#L22

Because of the way that line is written, it always downloads the latest version of the onboarding template. 1.2.1 introduces additional [runtime parameters](https://github.com/F5Networks/terraform-azure-bigip-module/blob/v1.2.0/f5_onboard.tmpl#L30). Because they do not exist in earlier versions of the module, all modules prior to 1.2.1 will fail upon initial configuration.

**Comment by RavinderReddyF5** [comment]
hi @mjmenger , yes i added HOSTNAME RUNTIME Parameter to set HOSTNAME to BIGIP from v1.2.1, and we getting DO config from URL which will always be latest config file will be downloaded. best is to upgrade v1.2.1.

**Comment by RavinderReddyF5** [comment]
let me try if i can make anything based on HOSTNAME value not set.
