### ISSUE TITLE
Please update the documentation

### ISSUE THREAD

**Issue by krzkal91** [F5Networks/terraform-azure-bigip-module#20]
Hi,

I have recently encountered an issue with the very same symptoms as in https://support.f5.com/csp/article/K26203562. 

This was a result of - my guess - providing the public ssh key together with the userpass authentication details.

Is the Public Key parameter still mandatory? The provided examples do not have it declared, however, the documentation still states that it is mandatory.

Could you please update the documentation section: https://github.com/F5Networks/terraform-azure-bigip-module#required-input-variables? Probably this part was omitted in the previous Readme updates, when the key-based authentication was the only way to go (my guess, again).

Cheers

**Comment by trinaths** [comment]
Created [INFRAANO-798] for internal tracking
