### ISSUE TITLE
Support to associate ASGs to network interfaces

### ISSUE THREAD

**Issue by AbhishekBatapati22** [F5Networks/terraform-azure-bigip-module#22]
As part of F5s deployment in Azure, we do have NSG rules defined using ASGs.

Current bigip module do not support ASG association. Without this support we cannot define NSG rules using ASGs. Using only IPs is a concern as we have other instances in mgmt subnet we do not want those instances to have access to F5s.

We are already passing in subnets and nsg information to bigip module.
If bigip module support ASG association then it will help us to define NSG rules before deploying F5s.

**Comment by KrithikaChidambaram** [comment]
Hi, this is added to the our backlog, internal tracking id is: INFRAANO-932, thanks!

**Comment by RavinderReddyF5** [comment]
Hi @AbhishekBatapati22 fixed in v1.2.7
