### ISSUE TITLE
private_addresses in outputs.tf incorrect values

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-azure-bigip-module#26]
The output gathered from the module 'private_addresses' is not fully correct. There are multiple NICs in the output as well as item entires for 'private_ip' and 'private_ips' with each values how a singular IP address for the first and multiple IPs for the latter. This is not the case.

## Current Behavior
Output for 'private_address' has mixed results as some code lines need to point to either the singular or pluraral of 'address' or 'addresses'. Notice that the mgmt NIC block is correct. The public_private block is not as private_ip is gathering from private_ip_addresses returning multiple instead of one. The external_private block is similiar behavior. The internal_private has both entries pointing to singular IP...as a result private_ip and private_ips both return a single IP.

Example current...
```
output "private_addresses" {
  description = "List of BIG-IP private addresses"
  value = {
    mgmt_private = {
      private_ip  = concat(azurerm_network_interface.mgmt_nic.*.private_ip_address)
      private_ips = concat(azurerm_network_interface.mgmt_nic.*.private_ip_addresses)
    }
    public_private = {
      private_ip  = concat(azurerm_network_interface.external_public_nic.*.private_ip_addresses)
      private_ips = concat(azurerm_network_interface.external_public_nic.*.private_ip_addresses)
    }
    external_private = {
      private_ip  = concat(azurerm_network_interface.external_nic.*.private_ip_addresses)
      private_ips = concat(azurerm_network_interface.external_nic.*.private_ip_addresses)
    }
    internal_private = {
      private_ip  = concat(azurerm_network_interface.internal_nic.*.private_ip_address)
      private_ips = concat(azurerm_network_interface.internal_nic.*.private_ip_address)
    }
  }
}
```

## Expected behavior
Output should show one IP for 'private_ip' and multiple values for 'private_ips'. This can be fixed by updating the code block. 

```
output "private_addresses" {
  description = "List of BIG-IP private addresses"
  value = {
    mgmt_private = {
      private_ip  = concat(azurerm_network_interface.mgmt_nic.*.private_ip_address)
      private_ips = concat(azurerm_network_interface.mgmt_nic.*.private_ip_addresses)
    }
    public_private = {
      private_ip  = concat(azurerm_network_interface.external_public_nic.*.private_ip_address)
      private_ips = concat(azurerm_network_interface.external_public_nic.*.private_ip_addresses)
    }
    external_private = {
      private_ip  = concat(azurerm_network_interface.external_nic.*.private_ip_address)
      private_ips = concat(azurerm_network_interface.external_nic.*.private_ip_addresses)
    }
    internal_private = {
      private_ip  = concat(azurerm_network_interface.internal_nic.*.private_ip_address)
      private_ips = concat(azurerm_network_interface.internal_nic.*.private_ip_addresses)
    }
  }
}
```

**Comment by JeffGiroux** [comment]
As a workaround, my example output.tf file pulls from the module output private_addresses with an 'element' function. I grab the first element after drilling down the block a bit.

```
output "bigip-private-ips" {
  description = "The private ip address for BIG-IP"
  value       = element(module.bigip.*.private_addresses.public_private.private_ip, 0)
}
```

The above method gives me the first self IP address associated with the NIC on the external NIC when public IP use case is in play. Otherwise same applies to "external_private" depending on use case (public IP needed or not).

**Comment by RavinderReddyF5** [comment]
@JeffGiroux thanks for noticing this and letting us know with solution. Tracking through : INFRAANO-823
