### ISSUE TITLE
Network interface ID needed in output

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-azure-bigip-module#29]
User would like to take network interface IDs and use the value in other resources such as Azure Gateway Load Balancer. However, the Azure GWLB object requires a network interface ID as well as the IP. Based on the current BIG-IP module, the ID of the network interface is needed along with the IP. The IP addresses are already in the output. We are missing the ID.

For example, a GWLB block looks like...
```
resource "azurerm_network_interface_backend_address_pool_association" "gwlb_backend_pool_association" {
  count                   = xxx
  network_interface_id    = xxx
  ip_configuration_name   = xxx
  backend_address_pool_id = xxx
}
```

Therefore, we need the interface IDs in the output broken out by external, internal, mgmt in order to grab the value and use in other resources. Example output needed in module looks like below...

```
output ext_eni_id {
  description = "Id of external network interface"
  value       = azurerm_network_interface.external_public_nic.*.id
}

output ext_eni_ipconfig_name {
  description = "Name of IPConfigs on first ext network interface"
  value       = azurerm_network_interface.external_public_nic[0].ip_configuration.*.name
}
```

**Comment by JeffGiroux** [comment]
## Workaround
Given the current naming of the BIG-IP and network interfaces with prefix and suffix, the only workaround is to export the device ID, then extract the prefix and buildSuffix of the BIG-IP, remove rest of name, then make a data resource for azure_network_interface in order to query the NIC name to retrieve ID.

Example, I added bigip instance IDs to my output. Now, I can see the VM name which is girouxgwlb-12fe-f5vm01. 

```
bigip_instance_ids = [
  "/subscriptions/77c6ebef-d849-4527-a355-742d8d7d3fdc/resourceGroups/girouxgwlb-rg-f091/providers/Microsoft.Compute/virtualMachines/girouxgwlb-12fe-f5vm01",
  "/subscriptions/77c6ebef-d849-4527-a355-742d8d7d3fdc/resourceGroups/girouxgwlb-rg-f091/providers/Microsoft.Compute/virtualMachines/girouxgwlb-5e05-f5vm01",
```

I would need to parse the VM name, remove "-f5vm01", then append the name of the network interface depending on how the BIG-IP module is naming it...currently it is named as follows in the BIG-IP module code...

```
resource "azurerm_network_interface" "external_nic" {
  count               = length(local.external_private_subnet_id)
  name                = "${local.instance_prefix}-ext-nic-${count.index}"
```

The output being "girouxgwlb-12fe-ext-nic-public-0". So...again, I need to take VM name, use only a portion of the name, then append "-ext-nic-public-0" then make a data resource to retrieve the ID.

**Comment by JeffGiroux** [comment]
Please make sure ID of all configured network interfaces are in the output.

**Comment by RavinderReddyF5** [comment]
Hi @JeffGiroux , Issue fixed in v1.2.5

**Comment by JeffGiroux** [comment]
I do not see this anywhere in the code, but yet it shows fixed. Where in outputs.tf are the NIC IDs?

**Comment by nephinjohn** [comment]
@RavinderReddyF5 was this checked in?  I also don't see the NIC IDs
