### ISSUE TITLE
[BUG] Management static private IPs do not work

### ISSUE THREAD

**Issue by ShachafGoldstein** [F5Networks/terraform-azure-bigip-module#36]
https://github.com/F5Networks/terraform-azure-bigip-module/blob/0cf879e439bda61f0561e2445a6cc6a1def87faf/main.tf#L329
the logic here is actually on public IP and not private.

the internal/external ones have a good logic.

**Comment by KrithikaChidambaram** [comment]
Hi, could you please elaborate the issue?

**Comment by ShachafGoldstein** [comment]
If I remember correctly the logic there ignores the scenario where you have only private ip for mgmt without public ip.

For that case you have the local of mgmt_private_ip_primary which is never used I can the code.

Currently you cannot deploy with this model a private only deployment without doing changes

**Comment by KrithikaChidambaram** [comment]
Hi, can you please share the main.tf file?

**Comment by guyopal** [comment]
Here you go @KrithikaChidambaram
[main.txt](https://github.com/F5Networks/terraform-azure-bigip-module/files/10202213/main.txt)

**Comment by guyopal** [comment]
Hi @KrithikaChidambaram, any news?

**Comment by KrithikaChidambaram** [comment]
Hi, thanks for reporting. Internal tracking ID for this issue is: INFRAANO-1050, thanks!

**Comment by RavinderReddyF5** [comment]
Hi @ShachafGoldstein @guyopal  fixed in v1.2.7
