### ISSUE TITLE
Template_file not compatible with M1 and terraform versions

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-azure-bigip-module#38]
The template provider is causing terraform initialize errors for M1 users. The data template_file resource was to be used prior to terraform .11 and now .12 and on should use templatefile instead. Please update all the Azure BIG-IP code to remove data template_file resources and use local templatefile instead.

## error
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.

**Comment by JeffGiroux** [comment]
Bad blocks...

# in the data blocks
data "template_file" "init_file" {
  template = file("${path.module}/${var.script_name}.tmpl")

data "template_file" "clustermemberDO1" {

data "template_file" "clustermemberDO2" {

data "template_file" "clustermemberDO3" {

# in the bigip virtual machine custom_data
  custom_data                     = base64encode(coalesce(var.custom_user_data, data.template_file.init_file.rendered))

**Comment by JeffGiroux** [comment]
## fix
Remove data template_file and replace with templatefile instead. Example structure...

locals {
  f5_onboard1 = templatefile("${path.module}/f5_onboard.tmpl", {
    regKey                     = var.license1
    f5_username                = var.f5_username
    f5_password                = var.f5_password
    az_keyvault_authentication = var.az_keyvault_authentication
    vault_url                  = var.az_keyvault_authentication ? var.keyvault_url : ""

**Comment by KrithikaChidambaram** [comment]
Hi Jeff, Internal tracking ID for this request is: INFRAANO-921, thanks!
