### ISSUE TITLE
Change linux resource to azure_linux_virtual_machine

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-azure-bigip-module#4]
The BIG-IP is deployed now with the azurerm_virtual_machine resource. There is a new resource that has greater flexibilty called https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine. Please look into updating the module to support this.

**Comment by JeffGiroux** [comment]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine

Note:
The azurerm_virtual_machine resource has been superseded by the [azurerm_linux_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine) and [azurerm_windows_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine) resources. The existing azurerm_virtual_machine resource will continue to be available throughout the 2.x releases however is in a feature-frozen state to maintain compatibility - new functionality will instead be added to the azurerm_linux_virtual_machine and azurerm_windows_virtual_machine resources.

**Comment by trinaths** [comment]
Created [INFRAANO-703] for internal tracking.

**Comment by RavinderReddyF5** [comment]
@JeffGiroux fixed in v1.2.0
