### ISSUE TITLE
VM os disk size

### ISSUE THREAD

**Issue by mieel** [F5Networks/terraform-azure-bigip-module#55]
We noticed that the os disk size is fixed at 84 GB, and there is no variable available to change this.
Is there a specific reason for this?

We would like to specify a variable `os_disk_size` at deployment time so that we can avoid expanding the disk later on.

**Comment by pgouband** [comment]
Hi @mieel,

Thanks for your feedback.
The size is matching most of our customer requirements.

You can fork the module and change the disk size on main.tf file line 477 to adapt it to your environment.
