### ISSUE TITLE
Not able to login to module after using default module setup

### ISSUE THREAD

**Issue by letmetechyou** [F5Networks/terraform-azure-bigip-module#57]
When running the default configuration for this module i can login to the cli but not the gui.  When looking at the console in azure i get this image 
![image](https://github.com/F5Networks/terraform-azure-bigip-module/assets/51865837/77dc92b0-9036-4f96-afa5-de45dcf06414)

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1283.

**Comment by letmetechyou** [comment]
I was able to get in but had to follow this article https://my.f5.com/manage/s/article/K11140735

**Comment by pgouband** [comment]
Hi @letmetechyou,

Thanks for the feedback.
Can we close the issue?

**Comment by letmetechyou** [comment]
yes you can close this out.
