### ISSUE TITLE
Example for 1 NIC AZ Key Vault is using the incorrect Input Variable

### ISSUE THREAD

**Issue by thnguyenf5** [F5Networks/terraform-azure-bigip-module#67]
Line 103 of the example terraform deployment - https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/examples/bigip_azure_1nic_deploy_keyvault/main.tf
is using the incorrect input variable.

az_key_vault_authentication

On the main documentation - https://github.com/F5Networks/terraform-azure-bigip-module/tree/main, the input variable is defined as az_keyvault_authentication.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1537.
