### ISSUE TITLE
Azure OS Provisioning

### ISSUE THREAD

**Issue by thnguyenf5** [F5Networks/terraform-azure-bigip-module#68]
Getting an error when trying to deploy to Azure.  Sometimes it deploys without issue but many times I get this error.

Error: waiting for creation of Linux Virtual Machine: (Name "thnguyen-tf.bigip1.f5devtest.lab" / Resource Group "thnguyen-rg"): Code="OSProvisioningTimedOut" Message="OS Provisioning for VM 'thnguyen-tf.bigip1.f5devtest.lab' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. For details on how to check current provisioning state of Windows VMs, refer to https://aka.ms/WindowsVMLifecycle and Linux VMs, refer to https://aka.ms/LinuxVMLifecycle."

I set the sleep_time variable to 20 mins but the results are still inconsistent.  Are there additional timers that can be configured in the main.tf file?

**Comment by pgouband** [comment]
Hi @thnguyenf5,

Are you using the examples from this repo? Or have you done modifications?

You found the sleep_time variable to be modified:
https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/variables.tf

```ansible
variable "sleep_time" {
  type        = string
  default     = "300s"
  description = "The number of seconds/minutes of delay to build into creation of BIG-IP VMs; default is 250. BIG-IP requires a few minutes to complete the onboarding process and this value can be used to delay the processing of dependent Terraform resources."
}
```

**Comment by thnguyenf5** [comment]
Yes I've deployed both ways.  With an example in the repo and also with the customization of the sleep_time variable.  Does the sleep_time variable affect the OSProvisioningTimeOut I will be seeing?

As an FYI, I tried this deployment to Azure US East

**Comment by thnguyenf5** [comment]
Yes this issue is reproducible.  We are using the BIG-IP BYOL image.

[signature_4005095171]<https://www.f5.com/>
Thanh Nguyen | Solutions Engineer III
M 281.787.6921


From: RavinderReddyF5 ***@***.***>
Date: Monday, June 17, 2024 at 11:01 AM
To: F5Networks/terraform-azure-bigip-module ***@***.***>
Cc: Thanh Nguyen ***@***.***>, Mention ***@***.***>
Subject: Re: [F5Networks/terraform-azure-bigip-module] Azure OS Provisioning (Issue #68)
CAUTION: This email has been sent from an external source. Do not click links, open attachments, or provide sensitive business information unless you can verify the sender’s legitimacy.


Hi @thnguyenf5<https://github.com/thnguyenf5>, is this issue reproducible ?? may I know image details if issue persist

**Comment by RavinderReddyF5** [comment]
Hi @thnguyenf5 ,
did not see issue on my run, here is example I have used: https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/examples/bigip_azure_1nic_deploy_byol/main.tf#L35-L48

**Comment by RavinderReddyF5** [comment]
Hi @thnguyenf5 closing issue as per last comment, please reopen issue with reproduction steps
