### ISSUE TITLE
Where can you specify Big-IP version and Azure VM size for the build

### ISSUE THREAD

**Issue by difzhao** [F5Networks/terraform-azure-bigip-module#69]
Hi team, I am new to coding in general and I am learning to use this terraform code to deploy the F5 in Azure. I am modifying the scripts to fit my need. I can't find where you would specify the BigIP version and Azure instance size for the build. Could you point me to the right direction? Thanks!

**Comment by pgouband** [comment]
Hi @difzhao,

Check this page:
https://clouddocs.f5.com/products/orchestration/terraform/latest/BIG-IP/bigip-modules/azure.html

I think you are looking for:
f5_instance_type: Specifies the size of the virtual machine.

f5_image_name: 5 SKU (image) you want to deploy. Note: The disk size of the VM will be determined based on the option you select. Important: If intending to provision multiple modules, ensure the appropriate value is selected, such as AllTwoBootLocations or AllOneBootLocation.

f5_version: It is set to default to use the latest software.

**Comment by difzhao** [comment]
Thanks @pgouband ! I will dig in this document. Will report back if I run into problems.
