### ISSUE TITLE
Add enable_ip_forwarding Option in mgmt_nic (L299 of main.tf)

### ISSUE THREAD

**Issue by jokoyuliantoro** [F5Networks/terraform-azure-bigip-module#75]
In 1NIC deployment, based on https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/main.tf, the mgmt_nic interface (https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/main.tf#L299) does not have "enable_ip_forwarding" option exposed like external_nic (https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/main.tf#L322) and external_public_nic (https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/main.tf#L348) which has "enable_ip_forwarding" option exposed.

Please help to adjust the https://github.com/F5Networks/terraform-azure-bigip-module/blob/main/main.tf#L299 part to include the "enable_ip_forwarding" option. This change also shows the F5 supportability of 1NIC deployment having the IP forwarding enabled on mgmt_nic.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1686.

**Comment by RavinderReddyF5** [comment]
Hi @jokoyuliantoro , issue fixed in v1.2.19, please open new issue if any issue observed
