### ISSUE TITLE
Support for New Azurerm 3.x provider

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-azure-bigip-module#9]
azure released the latest 3.x terraform provider March 24 2022. New resources, fixed resources, deprecated...etc. Please consider looking into 3.x and validate functionality with new provider version.
 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide

**Comment by trinaths** [comment]
Created [INFRAANO-735] for internal tracking.

**Comment by RavinderReddyF5** [comment]
@JeffGiroux fixed in v1.2.0
